services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-PeopleRegistry!1}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    # TCP healthcheck (no sqlcmd needed inside this image)
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - app-network
  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql_init
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-PeopleRegistry!1}
    volumes:
      - ../task_1_sql:/scripts:ro
    entrypoint: ["/bin/bash", "-c"]
    command: |
      set -e
      echo "SQL Server ready. Applying scripts..."
      until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" >/dev/null 2>&1; do
        sleep 2
      done
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$$MSSQL_SA_PASSWORD" -i /scripts/01_create_tables.sql
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "$$MSSQL_SA_PASSWORD" -i /scripts/02_seed_datas.sql
      echo "DB init completed."
    restart: "no"
    networks:
      - app-network
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: pr_backend
    working_dir: /app/src/Backend/PeopleRegistry.Api
    volumes:
      - ../task_2_webapp:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=mssql;Database=PeopleDb_Task2;User Id=sa;Password=${MSSQL_SA_PASSWORD:-PeopleRegistry!1};TrustServerCertificate=True;Encrypt=False;
    ports:
      - "8080:8080"
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: >
      bash -lc "
        dotnet restore &&
        dotnet build &&
        dotnet run --no-build --urls http://0.0.0.0:8080
      "
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - app-network
  frontend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: pr_frontend
    working_dir: /app/src/Frontend
    volumes:
      - ../task_2_webapp:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5173
      - Backend__BaseUrl=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    command: >
      bash -lc "
        dotnet restore &&
        dotnet build &&
        dotnet run --no-build --urls http://0.0.0.0:5173
      "
    networks:
      - app-network
volumes:
  mssql_data:
networks:
  app-network:
    driver: bridge